import { MigrationInterface, QueryRunner } from "typeorm";

export class NamingStrategy1684927328962 implements MigrationInterface {
    name = 'NamingStrategy1684927328962'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_49acb911ee20b02f86ec532a122"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_c93f22720c77241d2476c07cabf"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "FK_d869ee46445a391f13451d287f5"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_085156de3c3a44eba017a6a0846"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP CONSTRAINT "FK_b43c2b159b975d6f0f9828f563f"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP CONSTRAINT "FK_3bf1369e81b12358ba268f7f689"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "FK_5d1711e6796df7846e2a5df4f08"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "FK_a447a15e11df38648f721c83b44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d1711e6796df7846e2a5df4f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a447a15e11df38648f721c83b4"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "REL_49acb911ee20b02f86ec532a12"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "locationId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "middleName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" DROP COLUMN "postalCode"`);
        await queryRunner.query(`ALTER TABLE "user_location" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_location" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_location" DROP COLUMN "postalCode"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "restaurantId"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customerName"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customerEmail"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customerPhone"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "REL_d869ee46445a391f13451d287f"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "locationId"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "shortDescription"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "logoUrl"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "coverUrl"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "restaurantId"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "coverUrl"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "menuId"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "restaurantId"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "shortDescription"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "coverUrl"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "coverUrl"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "iconUrl"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_1a6c056397b970576f1d0a4d88c"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_a447a15e11df38648f721c83b44" PRIMARY KEY ("categoryId", "categoryName")`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP COLUMN "dishId"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_a447a15e11df38648f721c83b44"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_a70356d0ee713f0726a149f4215" PRIMARY KEY ("categoryName")`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_a70356d0ee713f0726a149f4215"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP COLUMN "categoryName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "middle_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "location_id" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_1523fb2aebce55b9e820122ee0e" UNIQUE ("location_id")`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" ADD "postal_code" character varying`);
        await queryRunner.query(`ALTER TABLE "user_location" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_location" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_location" ADD "postal_code" character varying`);
        await queryRunner.query(`ALTER TABLE "order" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ADD "customer_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "customer_email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "customer_phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "restaurant_id" uuid`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "short_description" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "logo_url" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "cover_url" character varying`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "location_id" uuid`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "UQ_cb49509e38be7c51870af77b8e6" UNIQUE ("location_id")`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "cover_url" character varying(1000)`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "restaurant_id" uuid`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "short_description" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "cover_url" character varying`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "menu_id" uuid`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "restaurant_id" uuid`);
        await queryRunner.query(`ALTER TABLE "category" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "category" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "category" ADD "cover_url" character varying(1000)`);
        await queryRunner.query(`ALTER TABLE "category" ADD "icon_url" character varying(1000)`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD "dish_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_27e808003eb5ec27d644c6e5200" PRIMARY KEY ("dish_id")`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD "category_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_27e808003eb5ec27d644c6e5200"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_0581eea4101e23423ffda4209fe" PRIMARY KEY ("dish_id", "category_id")`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD "category_name" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_0581eea4101e23423ffda4209fe"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_1a23550a4bc150dae9875e94a37" PRIMARY KEY ("dish_id", "category_id", "category_name")`);
        await queryRunner.query(`CREATE INDEX "IDX_27e808003eb5ec27d644c6e520" ON "dish_categories_category" ("dish_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b828bc70d8db6b522c9eff111" ON "dish_categories_category" ("category_id", "category_name") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1523fb2aebce55b9e820122ee0e" FOREIGN KEY ("location_id") REFERENCES "user_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_3edfcab660a53a1ac59e0e51911" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "FK_cb49509e38be7c51870af77b8e6" FOREIGN KEY ("location_id") REFERENCES "restaurant_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_a9c5473205703022c7a53a410c2" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dish" ADD CONSTRAINT "FK_67627299851ecd28a827bcaceb2" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dish" ADD CONSTRAINT "FK_54a6dff62586657498ee29f83ce" FOREIGN KEY ("restaurant_id") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "FK_27e808003eb5ec27d644c6e5200" FOREIGN KEY ("dish_id") REFERENCES "dish"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "FK_5b828bc70d8db6b522c9eff1119" FOREIGN KEY ("category_id", "category_name") REFERENCES "category"("id","name") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "FK_5b828bc70d8db6b522c9eff1119"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "FK_27e808003eb5ec27d644c6e5200"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP CONSTRAINT "FK_54a6dff62586657498ee29f83ce"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP CONSTRAINT "FK_67627299851ecd28a827bcaceb2"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_a9c5473205703022c7a53a410c2"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "FK_cb49509e38be7c51870af77b8e6"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_3edfcab660a53a1ac59e0e51911"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1523fb2aebce55b9e820122ee0e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b828bc70d8db6b522c9eff111"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27e808003eb5ec27d644c6e520"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_1a23550a4bc150dae9875e94a37"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_0581eea4101e23423ffda4209fe" PRIMARY KEY ("dish_id", "category_id")`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP COLUMN "category_name"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_0581eea4101e23423ffda4209fe"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_27e808003eb5ec27d644c6e5200" PRIMARY KEY ("dish_id")`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP COLUMN "category_id"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_27e808003eb5ec27d644c6e5200"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP COLUMN "dish_id"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "icon_url"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "cover_url"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "category" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "restaurant_id"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "menu_id"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "cover_url"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "short_description"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "dish" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "restaurant_id"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "cover_url"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP CONSTRAINT "UQ_cb49509e38be7c51870af77b8e6"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "location_id"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "cover_url"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "logo_url"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "short_description"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "restaurant" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "restaurant_id"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customer_phone"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customer_email"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "customer_name"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "order" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_location" DROP COLUMN "postal_code"`);
        await queryRunner.query(`ALTER TABLE "user_location" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_location" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" DROP COLUMN "postal_code"`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_1523fb2aebce55b9e820122ee0e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "location_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "middle_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD "categoryName" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_a70356d0ee713f0726a149f4215" PRIMARY KEY ("categoryName")`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD "categoryId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_a70356d0ee713f0726a149f4215"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_a447a15e11df38648f721c83b44" PRIMARY KEY ("categoryId", "categoryName")`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD "dishId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" DROP CONSTRAINT "PK_a447a15e11df38648f721c83b44"`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "PK_1a6c056397b970576f1d0a4d88c" PRIMARY KEY ("dishId", "categoryId", "categoryName")`);
        await queryRunner.query(`ALTER TABLE "category" ADD "iconUrl" character varying(1000)`);
        await queryRunner.query(`ALTER TABLE "category" ADD "coverUrl" character varying(1000)`);
        await queryRunner.query(`ALTER TABLE "category" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "category" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "coverUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "shortDescription" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "restaurantId" uuid`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "menuId" uuid`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "dish" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "coverUrl" character varying(1000)`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "restaurantId" uuid`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "coverUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "logoUrl" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "shortDescription" character varying(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "locationId" uuid`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "REL_d869ee46445a391f13451d287f" UNIQUE ("locationId")`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ADD "customerPhone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "customerEmail" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "customerName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order" ADD "restaurantId" uuid`);
        await queryRunner.query(`ALTER TABLE "order" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "order" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_location" ADD "postalCode" character varying`);
        await queryRunner.query(`ALTER TABLE "user_location" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_location" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" ADD "postalCode" character varying`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "restaurant_location" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "middleName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "locationId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "REL_49acb911ee20b02f86ec532a12" UNIQUE ("locationId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_a447a15e11df38648f721c83b4" ON "dish_categories_category" ("categoryId", "categoryName") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d1711e6796df7846e2a5df4f0" ON "dish_categories_category" ("dishId") `);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "FK_a447a15e11df38648f721c83b44" FOREIGN KEY ("categoryId", "categoryName") REFERENCES "category"("id","name") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dish_categories_category" ADD CONSTRAINT "FK_5d1711e6796df7846e2a5df4f08" FOREIGN KEY ("dishId") REFERENCES "dish"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dish" ADD CONSTRAINT "FK_3bf1369e81b12358ba268f7f689" FOREIGN KEY ("restaurantId") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dish" ADD CONSTRAINT "FK_b43c2b159b975d6f0f9828f563f" FOREIGN KEY ("menuId") REFERENCES "menu"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_085156de3c3a44eba017a6a0846" FOREIGN KEY ("restaurantId") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "restaurant" ADD CONSTRAINT "FK_d869ee46445a391f13451d287f5" FOREIGN KEY ("locationId") REFERENCES "restaurant_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_c93f22720c77241d2476c07cabf" FOREIGN KEY ("restaurantId") REFERENCES "restaurant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_49acb911ee20b02f86ec532a122" FOREIGN KEY ("locationId") REFERENCES "user_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
